[package]
name = "qemu-pac"
version = "0.0.30"
edition = "2021"
authors = ["Gallium70"]

[dependencies]
bare-metal = "1.0.0"
riscv = "0.10.0"
vcell = "0.1.3"

[features]
board_qemu = []
board_lrv = []
